######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 7 20:58:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FTPDialog.h
FORMS += FTPDialog.ui
SOURCES += FTPDialog.cpp main.cpp
