######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 15 08:12:40 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Hello.cpp
