######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 15 20:09:26 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
