######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 17 00:20:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainDialog.h
FORMS += maindialog.ui
SOURCES += main.cpp MainDialog.cpp
