######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 11 22:26:11 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
