######################################################################
# Automatically generated by qmake (2.01a) Sun Dec 15 08:19:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += Quit.cpp
